# Generated by Django 5.2.8 on 2025-11-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
