# Generated by Django 5.2.8 on 2025-11-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default=1, upload_to='foods/'),
            preserve_default=False,
        ),
    ]
