# Generated by Django 5.2.8 on 2025-11-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='addons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
