# Generated by Django 5.2.8 on 2025-11-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_cart_cartitem_paymenttransaction_profile_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=1, upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
